name: module_library_example
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  module_library:
    path: ../

  module_base:
    path: /Users/moyearzhou/StudioProjects/module_base
  #    git:
  #      url: https://github.com/moyearzhou/ModuleBase.git


dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.3.3


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
#  assets:
#    - assets/
#    - assets/items/
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
