name: module_library_example
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: '>=3.4.0'

dependencies:
  flutter:
    sdk: flutter
  module_library:
    path: ../

#  module_base:
##    path: /Users/moyearzhou/StudioProjects/module_base
#    git:
#      url: https://github.com/moyearzhou/ModuleBase.git
#      ref: feat/ohos

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.3.3

#dependency_overrides:
#  module_base:
#    path: /Users/moyearzhou/StudioProjects/module_base

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
  assets:
    - dev.env  # 仅 Debug 模式需要
    - production.env # 生产环境配置
#    - assets/
#    - assets/items/
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
